import { useEffect, useState } from "react";
import AlertMessage from "../common/AlertMessage";

const empty = { name: "", email: "", phone: "", company_name: "", source: "", priority: "medium", notes: "", owner_id: "" };
export default function LeadForm({ initialLead, owners, submitLabel, onSubmit }) {
  const [form, setForm] = useState(empty); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false);
  useEffect(() => { if (initialLead) setForm({ name: initialLead.name, email: initialLead.email ?? "", phone: initialLead.phone ?? "", company_name: initialLead.company_name ?? "", source: initialLead.source, priority: initialLead.priority, notes: initialLead.notes ?? "", owner_id: initialLead.owner?.id ?? "" }); }, [initialLead]);
  const update = (field) => (event) => setForm((value) => ({ ...value, [field]: event.target.value }));
  async function submit(event) { event.preventDefault(); setError(""); setSubmitting(true); try { await onSubmit({ ...form, email: form.email || null, phone: form.phone || null, company_name: form.company_name || null, notes: form.notes || null, owner_id: form.owner_id || null }); } catch (requestError) { setError(requestError.response?.data?.detail ?? "Unable to save the lead."); } finally { setSubmitting(false); } }
  return <form onSubmit={submit} noValidate>{error && <AlertMessage>{error}</AlertMessage>}<div className="row g-3"><div className="col-md-6"><label className="form-label" htmlFor="lead-name">Name</label><input required maxLength="150" className="form-control" id="lead-name" value={form.name} onChange={update("name")} /></div><div className="col-md-6"><label className="form-label" htmlFor="lead-source">Source</label><input required maxLength="100" className="form-control" id="lead-source" value={form.source} onChange={update("source")} /></div><div className="col-md-6"><label className="form-label" htmlFor="lead-email">Email</label><input type="email" maxLength="254" className="form-control" id="lead-email" value={form.email} onChange={update("email")} /></div><div className="col-md-6"><label className="form-label" htmlFor="lead-phone">Phone</label><input type="tel" maxLength="32" className="form-control" id="lead-phone" value={form.phone} onChange={update("phone")} /></div><div className="col-md-6"><label className="form-label" htmlFor="lead-company">Company</label><input maxLength="150" className="form-control" id="lead-company" value={form.company_name} onChange={update("company_name")} /></div><div className="col-md-6"><label className="form-label" htmlFor="lead-owner">Owner</label><select required className="form-select" id="lead-owner" value={form.owner_id} onChange={update("owner_id")}><option value="">Select an owner</option>{owners.map((owner) => <option key={owner.id} value={owner.id}>{owner.username ?? owner.email}</option>)}</select></div><div className="col-md-6"><label className="form-label" htmlFor="lead-priority">Priority</label><select className="form-select" id="lead-priority" value={form.priority} onChange={update("priority")}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></div><div className="col-12"><label className="form-label" htmlFor="lead-notes">Notes</label><textarea maxLength="2000" rows="4" className="form-control" id="lead-notes" value={form.notes} onChange={update("notes")} /></div></div><div className="mt-4"><button className="btn btn-primary" disabled={submitting}>{submitting ? "Saving…" : submitLabel}</button></div></form>;
}
